### ISSUE TITLE
Allow any PSR-17 and PSR-18 implementation to be used

### ISSUE THREAD

**Issue by LordSimal** [easybill/php-sdk#13]
It would be nice to not require `guzzlehttp/guzzle` and allow any [PSR-17 implementation](https://packagist.org/providers/psr/http-factory-implementation) and [PSR-18 implementation](https://packagist.org/providers/psr/http-client-implementation) to be used as a HTTP factory and HTTP client for this SDK

**Comment by PATROMO** [comment]
@LordSimal do you feel like making a pull request?

**Comment by LordSimal** [comment]
Not immediatly because I am not familiar with this code base. This is more of a general question if you feel like this would be able at all for this SDK? 
The main thing here would be if you use some sort of guzzle specific feature that is not defined in either PSR standard?
