### ISSUE TITLE
PHP 8.4 deprecation

### ISSUE THREAD

**Issue by LordSimal** [easybill/php-sdk#16]
```
deprecated: 8192 :: easybill\SDK\Client::request(): Implicitly marking parameter $body as nullable is deprecated, the explicit nullable type must be used instead on line 33 of /opt/atlassian/pipelines/agent/build/vendor/easybill/php-sdk/src/Client.php
```

With version 3.3.1

**Comment by BolZer** [comment]
Hi,

thank you for opening the issue. Gonna take a look tomorrow and release a new version shortly after.

**Comment by BolZer** [comment]
@LordSimal A new version is released on packagist. v3.4.0 will fix the deprecations. Closing this issue as it is fixed.
