### ISSUE TITLE
Update/Add Support for guzzlehttp/guzzle 7

### ISSUE THREAD

**Issue by LordSimal** [easybill/php-sdk#7]
I am just curious if it is possible to update/add support for Guzzle 7.

See https://github.com/guzzle/guzzle/blob/7.0.0/UPGRADING.md for what changed.

**Comment by PATROMO** [comment]
https://github.com/easybill/php-sdk/releases/tag/v3.0.0

**Comment by LordSimal** [comment]
well thanks 😄
